name: Automated Daily Commits

on:
  schedule:
    - cron: '0 0 * * *'  # Every 5 minutes for testing  
  workflow_dispatch:

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Git
        run: |
          git config --global user.name "Automated Commit Bot"
          git config --global user.email "bot@example.com"

      - name: Generate random commits
        run: |
          COMMIT_COUNT=$((RANDOM % 6 + 3))
          for ((i=1; i<=COMMIT_COUNT; i++)); do
            echo "$(date '+%Y-%m-%d %H:%M:%S') - Commit $i" >> commit_log.txt
            git add commit_log.txt
            git commit -m "api update $i on $(date '+%Y-%m-%d')"
            sleep 1
          done

      - name: Push changes
        run: |
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
